### PR TITLE
Qt patches

### PR DESCRIPTION
**Pull request by bdbcat**
Various changes to allow building for Qt/Android

### CODE REVIEW

**Comment by bdbcat** [comment]
Dan...
When accepted upstream, will this go into master branch, or somewhere else?

**Comment by transmitterdan** [comment]
Dave, I believe it will be in master but don’t know when they will merge.  I asked to at least put these changes in master before 3.2 is GA. I have a couple nits they are complaining about.  Working those now.  Thanks for this it really helped me along. Dan From: bdbcatSent: Friday, January 22, 2021 8:07 AMTo: transmitterdan/wxWidgetsCc: transmitterdan; State changeSubject: Re: [transmitterdan/wxWidgets] Qt patches (#4) Dan...When accepted upstream, will this go into master branch, or somewhere else?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bdbcat** [comment]
I may have one more patch, to the general wx configuration scripts.  There are a couple of Qt include files that do not get installed correctly by "make install" after configuration for Qt build.  I'll check again and let you know.

**Comment by transmitterdan** [comment]
Ok, I am running the CI builds now.  Takes few hours. Sent from Mail for Windows 10 From: bdbcatSent: Friday, January 22, 2021 8:18 AMTo: transmitterdan/wxWidgetsCc: transmitterdan; State changeSubject: Re: [transmitterdan/wxWidgets] Qt patches (#4) I may have one more patch, to the general wx configuration scripts. There are a couple of Qt include files that do not get installed correctly by "make install" after configuration for Qt build. I'll check again and let you know.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by transmitterdan** [comment]
Dave, What is this commit doing? commit a9052b39882feb65ca8dacc6d34dcb5832de770f Thanks,Dan From: bdbcatSent: Friday, January 22, 2021 8:18 AMTo: transmitterdan/wxWidgetsCc: transmitterdan; State changeSubject: Re: [transmitterdan/wxWidgets] Qt patches (#4) I may have one more patch, to the general wx configuration scripts. There are a couple of Qt include files that do not get installed correctly by "make install" after configuration for Qt build. I'll check again and let you know.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bdbcat** [comment]
Dan
That was an old commit from the wxWidgets master branch, I think.  Anyway, not my work. Somehow leaked into my local branch...
Should I remove it from the PR, and re-submit?

**Comment by transmitterdan** [comment]
Dave,

I need to clean up the PR as it got pretty ragged as things progressed. Also, the wx team broke the CI process on Friday so I’m waiting for that to clear up. In the mean time please have a look at my PR in the wxWidgets repository for QA purposes. If something extra made it in perhaps something got lost too.

I will try to squash and rebase the PR to make it less ugly. Probably will close it and submit new more compact one.

Thanks,
Dan

**Comment by bdbcat** [comment]
Dan.
diff against master looks fine now.
I'll try a test build against your repo today.

**Comment by transmitterdan** [comment]
Dave, Update for Sunday: I squashed and rebased the update against most recent master branch of wxWidgets.  This new branch is in my repo at qtUpdate (not qtUpdates | qtPatches).  It would be a good idea to build against that branch as a sanity check.  I tried to drop any duplicate commits.  The diff should be the same except possibly for whitespace plus I optimized away variable m_started (it was always set to either 0 or 1 but never referenced AFAICT). Finally, there are still a few comments from Maarten (wxWidgets maintainer).  He seems willing to merge if we answer a few questions and comments.@vadz commented on this pull request.Thanks for the update!In src/qt/window.cpp:> ++            //  Allow processing of QGesture events, if generated upstream.+            m_qtWindow->setAttribute(Qt::WA_AcceptTouchEvents);+            m_qtWindow->grabGesture(Qt::PanGesture);+Do we really need to do it here in addition to doing it in EnableTouchEvents()?In src/qt/glcanvas.cpp:> +    QGestureRecognizer* pPanRecognizer = new PanGestureRecognizer();+    QGestureRecognizer::registerRecognizer(pPanRecognizer);+I don't know if there is any drawback in doing this unconditionally or if we should only do when touch events are enabled.Maybe a comment here could help clarify things?  Thanks,Dan  From: bdbcatSent: Sunday, January 24, 2021 8:20 AMTo: transmitterdan/wxWidgetsCc: transmitterdan; State changeSubject: Re: [transmitterdan/wxWidgets] Qt patches (#4) Dan.diff against master looks fine now.I'll try a test build against your repo today.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bdbcat** [comment]
Dan...
Building/testing qtUpdates now.
I'll take a look at @vadz comments after confirming the merge builds and runs OK.

**Comment by transmitterdan** [comment]
Dave, Please use qtUpdate (not qtUpdates). Dan From: bdbcatSent: Sunday, January 24, 2021 11:19 PMTo: transmitterdan/wxWidgetsCc: transmitterdan; State changeSubject: Re: [transmitterdan/wxWidgets] Qt patches (#4) Dan...Building/testing qtUpdates now.I'll take a look at @vadz comments after confirming the merge builds and runs OK.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
