### PR TITLE
Qt update

### PR DESCRIPTION
**Pull request by bdbcat**

### CODE REVIEW

**Comment by bdbcat** [comment]
Dan...
Sorry, this PR contains some commits to master from other contributors, posted yesterday.
Is it OK?

**Comment by transmitterdan** [comment]
I will look at it today and see if it can be sorted. I’m sure it can.

Dan

**Comment by transmitterdan** [comment]
Dave, From what I can tell there are only 2 real new commits from you as follows: 4b1f64b4ce6023eedcb0f75e4ddf97f45f2d29bee06920fce537c339eac8e5149144be3c849ebdf5 Is this right?  If so, I think I can cherry pick these two commits and have a clean PR. Thanks,Dan

**Comment by transmitterdan** [comment]
Dave… Did the cherry pick and pushed your commits to qtUpdate branch.  See if it all looks final now. Thanks,Dan From: bdbcatSent: Monday, January 25, 2021 9:27 PMTo: transmitterdan/wxWidgetsCc: SubscribedSubject: Re: [transmitterdan/wxWidgets] Qt update (#5) Dan..Sorry, this PR contains some commits to master from other contributors, posted yesterday.Is it OK?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bdbcat** [comment]
Dan..
Looks fine now. No additional comments from @vadz yet...

**Comment by transmitterdan** [comment]
Closed via cherry pick of 2 relevant commits.

**Pull request closed without merging**
